# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.srcs/sources_1/ip/cascaded_integrator_comb/cascaded_integrator_comb.xci
# IP: The module: 'cascaded_integrator_comb' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.srcs/sources_1/ip/cascaded_integrator_comb/cascaded_integrator_comb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cascaded_integrator_comb'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.srcs/sources_1/ip/cascaded_integrator_comb/cascaded_integrator_comb.xci
# IP: The module: 'cascaded_integrator_comb' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.srcs/sources_1/ip/cascaded_integrator_comb/cascaded_integrator_comb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cascaded_integrator_comb'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
