# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==cascaded_integrator_comb || ORIG_REF_NAME==cascaded_integrator_comb}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==half_band_FIR || ORIG_REF_NAME==half_band_FIR}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==lp_FIR || ORIG_REF_NAME==lp_FIR}]]
