# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files c:/Users/coltmw/Downloads/Nexys4_PDM_RefProj/Nexys4_PDM_RefProj/ipcore_dir_hb/ord15_1136-3864.coe
add_files c:/Users/coltmw/Downloads/Nexys4_PDM_RefProj/Nexys4_PDM_RefProj/ipcore_dir_lp/ord161_13_15_96kHz.coe
add_files -quiet C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.runs/cascaded_integrator_comb_synth_1/cascaded_integrator_comb.dcp
set_property used_in_implementation false [get_files C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.runs/cascaded_integrator_comb_synth_1/cascaded_integrator_comb.dcp]
add_files -quiet C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.runs/half_band_FIR_synth_1/half_band_FIR.dcp
set_property used_in_implementation false [get_files C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.runs/half_band_FIR_synth_1/half_band_FIR.dcp]
add_files -quiet C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.runs/lp_FIR_synth_1/lp_FIR.dcp
set_property used_in_implementation false [get_files C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.runs/lp_FIR_synth_1/lp_FIR.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.srcs/sources_1/new/delta_sigma.v
  C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.srcs/sources_1/new/main_array.v
}
read_vhdl -library xil_defaultlib C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.srcs/sources_1/imports/Nexys4_PDM_RefProj/hp_rc.vhd
read_xdc C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.srcs/constrs_1/new/main_array.xdc
set_property used_in_implementation false [get_files C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.srcs/constrs_1/new/main_array.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array/microphone-array.cache/wt [current_project]
set_property parent.project_dir C:/Users/coltmw/Documents/GitHub/ecen4024-microphone-array/microphone-array [current_project]
catch { write_hwdef -file main_array.hwdef }
synth_design -top main_array -part xc7a100tcsg324-1
write_checkpoint main_array.dcp
report_utilization -file main_array_utilization_synth.rpt -pb main_array_utilization_synth.pb
